MisContactos/APP/urls.py
from django.urls import path
from APP.views import *

urlpatterns = [
    path('', inicio, name='inicio'),
    path('agregar_contacto', agregar_contacto, name='agregarContacto'),
    path('agregar_familiar', agregar_familiar, name='agregarFamiliar'),
    path('agregar_amigo', agregar_amigo, name='agregarAmigo'),
    path('agregar_colega', agregar_colega, name='agregarColega'),
    path('busqueda_nombre', busqueda_nombre, name="busquedaFormulario"),
    path('busqueda_nombre_post', busqueda_nombre_post, name="busquedaFormulario_Post"),
    path('busqueda_nombre_post_amigo', busqueda_nombre_post_amigo, name="busquedaFormulario_Post_Amigo"),
    path('busqueda_nombre_post_colega', busqueda_nombre_post_colega, name="busquedaFormulario_Post_colega"),
]

MisContactos/MisContactos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('APP/', include('APP.urls')),
    path('', lambda req: redirect('inicio')),
]

MisContactos/APP/models.py
from django.db import models

# Create your models here.
class Familiares(models.Model):
    nombre = models.CharField(max_length=30)
    email = models.EmailField()
    edad = models.IntegerField()
    registro = models.DateField()

class Amigos(models.Model):
    nombre = models.CharField(max_length=30)
    email = models.EmailField()
    edad = models.IntegerField()
    registro = models.DateField()

class Colegas(models.Model):
    nombre = models.CharField(max_length=30)
    email = models.EmailField()
    edad = models.IntegerField()
    registro = models.DateField()

MisContactos/APP/forms.py
from django import forms

class FormularioPersonas(forms.Form):
    nombre = forms.CharField(max_length=30)
    email = forms.EmailField()
    edad = forms.IntegerField()
    registro = forms.DateField()


class BusquedaFamiliarFormulario(forms.Form):
    nombre = forms.CharField(max_length=30)

class BusquedaAmigoFormulario(forms.Form):
    nombre = forms.CharField(max_length=30)

class BusquedaColegaFormulario(forms.Form):
    nombre = forms.CharField(max_length=30)

MisContactos/APP/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from APP.models import *
from APP.forms import *

# Create your views here.
def inicio(req):
        # Vista para mostrar todos los datos de las 3 tablas
    familiares = Familiares.objects.all()
    amigos = Amigos.objects.all()
    colegas = Colegas.objects.all()
    
    contexto = {
        'familiares': familiares,
        'amigos': amigos,
        'colegas': colegas,
    }
    
    return render(req, 'index.html', contexto)

def agregar_contacto(req):
    return render(req, 'agregar_contacto.html')

def agregar_familiar(req):
    # 2) chequeo que la info venga por verbo POST
    if req.method == 'POST':
        formulario = FormularioPersonas(req.POST)
        
        # 3) chequeo validaciones de los datos que recibo del formulario
        if formulario.is_valid():
            # 4) limpio el formulario
            data = formulario.cleaned_data
            
            # 5) inserto datos y guardo en db
            familiar = Familiares(nombre=data.get('nombre'), email=data.get('email'), edad=data.get('edad'), registro=data.get('registro'))
            familiar.save(data)
            
            messages.info(req,
                  f'Se ha agregado a: {familiar.nombre} a tus familiares.')
            
            # 6) redirijo a 
            return redirect('inicio')
    
    # 1) cargo el formulario vacio para que sea completado por el usuario
    contexto = {
        'form': FormularioPersonas()
    }
    return render(req, 'formulario.html', contexto)

def agregar_amigo(req):
    # 2) chequeo que la info venga por verbo POST
    if req.method == 'POST':
        formulario = FormularioPersonas(req.POST)
        
        # 3) chequeo validaciones de los datos que recibo del formulario
        if formulario.is_valid():
            # 4) limpio el formulario
            data = formulario.cleaned_data
            
            # 5) inserto datos y guardo en db
            amigo = Amigos(nombre=data.get('nombre'), email=data.get('email'), edad=data.get('edad'), registro=data.get('registro'))
            amigo.save(data)
            
            messages.info(req,
                  f'Se ha agregado a: {amigo.nombre} a tus amigos.')
            
            # 6) redirijo a 
            return redirect('inicio')
    
    # 1) cargo el formulario vacio para que sea completado por el usuario
    contexto = {
        'form': FormularioPersonas()
    }
    return render(req, 'formulario.html', contexto)


def agregar_colega(req):
    # 2) chequeo que la info venga por verbo POST
    if req.method == 'POST':
        formulario = FormularioPersonas(req.POST)
        
        # 3) chequeo validaciones de los datos que recibo del formulario
        if formulario.is_valid():
            # 4) limpio el formulario
            data = formulario.cleaned_data
            
            # 5) inserto datos y guardo en db
            colega = Colegas(nombre=data.get('nombre'), email=data.get('email'), edad=data.get('edad'), registro=data.get('registro'))
            colega.save(data)
            
            messages.info(req,
                  f'Se ha agregado a: {colega.nombre} a tus colegas.')
            
            # 6) redirijo a 
            return redirect('inicio')
    
    # 1) cargo el formulario vacio para que sea completado por el usuario
    contexto = {
        'form': FormularioPersonas()
    }
    return render(req, 'formulario.html', contexto)


def busqueda_nombre(request):
    # Vista para entregar formulario y mostrar lo filtrado
    contexto = {
        'form': BusquedaFamiliarFormulario(),
        'formAmigo': BusquedaAmigoFormulario(),
        'formColega': BusquedaColegaFormulario(),
    }
    return render(request, 'formulario_filtrado.html', contexto)



def busqueda_nombre_post(request):
    # Recibo el nombre para filtrar
    nombre= request.GET.get('nombre')

    nombres = Familiares.objects.filter(nombre__icontains = nombre)
    # paso los datos que encontro al contexto
    contexto = {
        'nombres' : nombres
    }
    return render(request, 'formulario_filtrado_resultado.html', contexto)


def busqueda_nombre_post_amigo(request):
    # Recibo el nombre para filtrar
    nombre  = request.GET.get('nombre')
    # paso los datos que encontro al contexto
    nombres = Amigos.objects.filter(nombre__icontains = nombre)

    contexto = {
        'nombres' : nombres
    }
    return render(request, 'formulario_filtrado_resultado.html', contexto)

def busqueda_nombre_post_colega(request):
    nombre  = request.GET.get('nombre')
    # Recibo el nombre para filtrar
    nombres = Colegas.objects.filter(nombre__icontains = nombre)
    # paso los datos que encontro al contexto
    contexto = {
        'nombres' : nombres
    }
    return render(request, 'formulario_filtrado_resultado.html', contexto)

MisContactos/templates/APP/Buscar.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
			crossorigin="anonymous"
		/>
		{% block title %}
		<title>HOME</title>
		{% endblock %}
	</head>
	<body>
		<!-- HEADER -->
		{% include 'base/header.html' %}

		<!-- MAIN -->
		{% block main %}
		<main>SOY EL HOME</main>


  		<form action="/APP/buscar" method="GET"> {% csrf_token %}

    	{{ form.as_p }}

    	<input type="submit" value="Buscar">
  		</form>


		{% endblock %}
		<!-- FOOTER -->
		{% include 'base/footer.html' %}
		<!-- bootstrap / JS -->
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
			crossorigin="anonymous"
		></script>
	</body>
</html>

MisContactos/templates/APP/BuscarContacto.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}

		{% block title %}
		<title>Buscar Contacto</title>
		{% endblock %}

		<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
	</head>
	<body>
		<!-- HEADER -->
		{% include 'base/header.html' %}

		<!-- MAIN -->
		{% block main %}
		<main>Buscar Contacto</main>
		<br>
		  {% for familiar in familiares %}
        El nombre del curso es {{familiar.nombre}} con la edad {{familiar.edad}} <br> <hr>
		{% endfor %}

		{% endblock %}

		<!-- FOOTER -->
		{% include 'base/footer.html' %}
<br>
<br>



	<table class="table">
  <thead>
    <tr>

      <th scope="col">Nombre</th>
      <th scope="col">Edad</th>
      <th scope="col">Email</th>
		<th scope="col">Registro</th>
    </tr>
  </thead>
  <tbody>
  	{% for familiar in familiares %}
    <tr>

		<td>{{familiar.nombre}}</td>
		<td>{{familiar.edad}}</td>
        <td>{{familiar.email}}</td>
        <td>{{familiar.registro}}</td>
    </tr>
      {% endfor %}
  </tbody>
</table>


	</body>


</html>

MisContactos/templates/APP/Resultado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hola</title>
</head>
<body>

</body>
</html>

MisContactos/templates/agregar_contacto.html
{% extends 'index.html' %} {% load static %} {% block styles %}
<link rel="stylesheet" href="{% static 'css/agregar_contacto.css'%}" />
{% endblock %} {% block title %}
<title>Agregar Contacto</title>
{% endblock %} {% block main %}
<main class="agregar_contacto-main">
    <div class="agregar_contacto-div-wrapper">
        <div class="mb-3 agregar_contacto-div">
            <a
                class="form-control agregar_contacto-a"
                href="{% url 'agregarFamiliar' %}"
                >AGREGAR FAMILIAR</a
            >
        </div>
        <div class="mb-3 agregar_contacto-div">
            <a
                class="form-control agregar_contacto-a"
                href="{% url 'agregarAmigo' %}"
                >AGREGAR AMIGO</a
            >
        </div>
        <div class="mb-3 agregar_contacto-div">
            <a
                class="form-control agregar_contacto-a"
                href="{% url 'agregarColega' %}"
                >AGREGAR COLEGA</a
            >
        </div>
    </div>
</main>
{% endblock %}

MisContactos/templates/base/footer.html
<footer
	style="
		background-color: #201f1d;
		color: #d1cdcc;
		width: 100%;
		padding: 15px;
		text-align: center;
		position: fixed;
		bottom: 0;
	"
>
	...Hecho con Django & más...
</footer>

MisContactos/templates/base/header.html
<header style="padding: 15px 0; background-color: #201f1d">
	<nav>
		<ul
			style="
				list-style: none;
				display: flex;
				justify-content: space-around;
			"
		>
			<li style="display: inline-block">
				<h5>
					<a
						style="text-decoration: none; color: #aa0d3f"
						href="{% url 'inicio' %}"
						>INICIO</a
					>
				</h5>
			</li>
			<li style="display: inline-block">
				<h5>
					<a
						style="text-decoration: none; color: #aa0d3f"
						href="{% url 'agregarContacto' %}"
						>AGREGAR CONTACTO</a
					>
				</h5>
			</li>
			<li style="display: inline-block">
				<h5>
					<a
						style="text-decoration: none; color: #aa0d3f"
						href="{% url 'busquedaFormulario' %}"
						>BUSCAR
					</a>
				</h5>
			</li>
		</ul>
	</nav>
</header>

MisContactos/templates/formulario.html
{% extends 'index.html' %} {% load static %} {% block styles %}
<link rel="stylesheet" href="{% static 'css/formulario.css'%}" />
{% endblock %} {% block title %}
<title>Formulario</title>
{% endblock %} {% block main %}
<main class="formulario-main">
    <form action="" method="POST" class="formulario-from">
        {% csrf_token %}

        <h4 class="formulario-h4">Información Personal:</h4>

        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                id="id_nombre"
                name="nombre"
            />
            <label for="id_nombre">Nombre y Apellido:</label>
        </div>
        <div class="form-floating mb-3">
            <input
                type="text"
                class="form-control"
                id="id_email"
                name="email"
            />
            <label for="email">Email:</label>
        </div>
        <div class="form-floating mb-3">
            <input
                type="number"
                class="form-control"
                id="id_edad"
                name="edad"
            />
            <label for="id_edad">Edad:</label>
        </div>
        <div class="form-floating mb-3">
            <input
                type="date"
                class="form-control"
                id="id_registro"
                name="registro"
            />
            <label for="id_registro">Registro:</label>
        </div>

        <div class="formulario-div-enviar">
            <input class="btn btn-secondary" type="submit" value="ENVIAR" />
        </div>
    </form>
</main>
{% endblock %}

MisContactos/templates/formulario_filtrado.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
			crossorigin="anonymous"
		/>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:ital,wght@1,700&family=Cinzel:wght@700&family=Monoton&family=Oswald&family=Playfair+Display:ital,wght@1,600&family=Pontano+Sans&family=Roboto&family=Syncopate&display=swap"
			rel="stylesheet"
		/>
		{% block title %}
		<title>HOME</title>
		{% endblock %}
	</head>
	<body
		style="
			font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS',
				sans-serif;
		"
	>
		<!-- HEADER -->
		{% include 'base/header.html' %}

		<!-- MAIN -->
		{% block main %}
		<main
			style="
				background-color: #252525;
				color: white;
				height: calc(100vh - 60px);
			"
		>
			<div class="container text-center">
				<div class="row">
					<!-- Familiares -->
					<div class="col">
						<form action="/APP/busqueda_nombre_post" method="GET">
							{% csrf_token %}
							<div class="card" style="width: 18rem">
								<ul class="list-group list-group-flush">
									<li class="list-group-item">
										Buscar Familiar
									</li>
									<li class="list-group-item">
										{{ form.as_p }}
									</li>
									<li class="list-group-item">
										<input type="submit" value="Buscar" />
									</li>
								</ul>
							</div>
						</form>
					</div>
					<!-- Amigos -->
					<div class="col">
						<form
							action="/APP/busqueda_nombre_post_amigo"
							method="GET"
						>
							{% csrf_token %}
							<div class="card" style="width: 18rem">
								<ul class="list-group list-group-flush">
									<li class="list-group-item">
										Buscar Amigos
									</li>
									<li class="list-group-item">
										{{ form.as_p }}
									</li>
									<li class="list-group-item">
										<input type="submit" value="Buscar" />
									</li>
								</ul>
							</div>
						</form>
					</div>

					<!-- Colegas -->
					<div class="col">
						<form
							action="/APP/busqueda_nombre_post_colega"
							method="GET"
						>
							{% csrf_token %}
							<div class="card" style="width: 18rem">
								<ul class="list-group list-group-flush">
									<li class="list-group-item">
										Buscar Colegas
									</li>
									<li class="list-group-item">
										{{ form.as_p }}
									</li>
									<li class="list-group-item">
										<input type="submit" value="Buscar" />
									</li>
								</ul>
							</div>
						</form>
					</div>
				</div>
			</div>

			<hr />
		</main>
		{% endblock %}

		<!-- FOOTER -->
		{% include 'base/footer.html' %}
		<!-- bootstrap / JS -->
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
			crossorigin="anonymous"
		></script>
	</body>
</html>

MisContactos/templates/formulario_filtrado_resultado.html
{% extends 'index.html' %} {% load static %} {% block styles %}
<link
    rel="stylesheet"
    href="{% static 'css/formulario_filtrado_resultado.css'%}"
/>
{% endblock %} {% block title %}
<title>Formulario</title>
{% endblock %} {% block link %}
<!-- CSS only -->
<link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
    crossorigin="anonymous"
/>
{% endblock %} {% block main %}
<main class="ffr-main">
    <h4 class="ffr-h4">Resultado de la búsqueda:</h4>
    {% csrf_token %}

    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Email</th>
                <th scope="col">Edad</th>
                <th scope="col">Registro</th>
            </tr>
        </thead>

        <tbody>
            {% for nombre in nombres %}
            <tr>
                <td>{{nombre.nombre}}</td>
                <td>{{nombre.email}}</td>
                <td>{{nombre.edad}}</td>
                <td>{{nombre.registro}}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</main>
{% endblock %}

MisContactos/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
            crossorigin="anonymous"
        />
        {% block styles %}
        <link rel="stylesheet" href="{% static 'css/index.css'%}" />
        {% endblock %}

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:ital,wght@1,700&family=Cinzel:wght@700&family=Monoton&family=Oswald&family=Playfair+Display:ital,wght@1,600&family=Pontano+Sans&family=Roboto&family=Syncopate&display=swap"
            rel="stylesheet"
        />
        {% block title %}
        <title>HOME</title>
        {% endblock %}
    </head>
    <body class="index-body">
        <!-- HEADER -->
        {% include 'base/header.html' %}

        <!-- MAIN -->
        {% block main %}
        <main class="index-main">
            <!-- mensajes -->
            {% for message in messages %}
            <div class="alert alert-success index-div-messages" role="alert">
                {{message}}
            </div>
            {% endfor %}
            <br />
            <h2 class="index-h2">MIS CONTACTOS</h2>
            <div>
                <h4>Familia</h4>
                <hr />
                <table class="table table-dark table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Email</th>
                            <th scope="col">Edad</th>
                            <th scope="col">Registro</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for familia in familiares %}
                        <tr>
                            <td>{{familia.nombre}}</td>
                            <td>{{familia.email}}</td>
                            <td>{{familia.edad}}</td>
                            <td>{{familia.registro}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <br />
                <hr />
                <h4>Amigos</h4>
                <hr />
                <table class="table table-dark table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Email</th>
                            <th scope="col">Edad</th>
                            <th scope="col">Registro</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for amigo in amigos %}
                        <tr>
                            <td>{{amigo.nombre}}</td>
                            <td>{{amigo.email}}</td>
                            <td>{{amigo.edad}}</td>
                            <td>{{amigo.registro}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <br />
                <hr />
                <h4>Colegas</h4>
                <hr />
                <table class="table table-dark table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Nombre</th>
                            <th scope="col">Email</th>
                            <th scope="col">Edad</th>
                            <th scope="col">Registro</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for colega in colegas %}
                        <tr>
                            <td>{{colega.nombre}}</td>
                            <td>{{colega.email}}</td>
                            <td>{{colega.edad}}</td>
                            <td>{{colega.registro}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <br />
            </div>
            <br />
        </main>

        {% endblock %}
        <!-- FOOTER -->
        {% include 'base/footer.html' %}
        <!-- bootstrap / JS -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous"
        ></script>
    </body>
</html>